version: "3.8"

services:
  app:
    build: .
    container_name: actus_php_app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:80"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: actus_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: actus_db
    ports:
      - "5432:5432"
    volumes:
      - ./bdd:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
