ALTER TABLE articles ADD COLUMN meta_description VARCHAR(255), ADD COLUMN alt_text VARCHAR(255);
CREATE TABLE imagearticle (id SERIAL PRIMARY KEY, article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE, image_path VARCHAR(255) NOT NULL, alt_text VARCHAR(255), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);
